### ISSUE TITLE
No networks found in SIM card's Network operators

### ISSUE THREAD

**Issue by 1kevin335200** [z2-dev/android_device_zuk_z2_row#1]
That means i cannot select the network operator manually. Sometimes due to low signals my phone may switch to some unwillingly operators and it's hard to switch back.
I think it's a universal problem. If i need to upload logs please tell me. Thanks a lot
![image](https://user-images.githubusercontent.com/15524267/34566172-e8d79c2e-f15d-11e7-9462-a9eef5b6d9d6.png)

**Comment by cosmedd** [comment]
I couldn't reproduce that issue with cm-14.1. But in any case I no longer work on Nougat.
